# Generated by Django 5.2.5 on 2025-08-08 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crawler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="爬虫名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="爬虫描述"),
                ),
                (
                    "script_path",
                    models.CharField(max_length=255, verbose_name="脚本路径"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "爬虫",
                "verbose_name_plural": "爬虫",
            },
        ),
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "已失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="参数"),
                ),
                (
                    "crawler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.crawler",
                        verbose_name="爬虫",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取工作",
                "verbose_name_plural": "爬取工作",
            },
        ),
        migrations.CreateModel(
            name="CrawlResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=1024, verbose_name="URL")),
                ("data", models.JSONField(verbose_name="提取的数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crawler.crawljob",
                        verbose_name="爬取工作",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬取结果",
                "verbose_name_plural": "爬取结果",
            },
        ),
    ]
